#!/bin/sh

#<1> 配置区域
SDK_NAME=PayPlusSDK
SDK_VERSION=1.0.0
SDK_REPOPATH=https://github.com/jinmaizhonghe/${SDK_NAME}.git
SDK_HOMEPAGE=https://github.com/jinmaizhonghe/${SDK_NAME}
SDK_UPDATE_DESCRIPTION="钱麦众合移动端iOS版SDK."
SDK_PODFILE_NAME=${SDK_NAME}.podspec
SDK_AUTOR_NAME=Sam
SDK_AUTOR_EMAIL=security@jia007.com
SDK_PATH=PayPlusSDK


configuration_podsepc ()
{
  echo "Pod::Spec.new do |s|" 															                             > $SDK_PODFILE_NAME
  echo "  s.name         = '$SDK_NAME'" 												                         >> $SDK_PODFILE_NAME
  echo "  s.version      = '$SDK_VERSION'" 												                       >> $SDK_PODFILE_NAME
  echo "  s.summary      = '$SDK_NAME'" 												                         >> $SDK_PODFILE_NAME
  echo "  s.description  = <<-DESC
                              PayPlusSDK是由金麦众合提供的聚合支付客户端一站式的集成解决方案，
                              PayPlusSDK大大的降低了开发者对各家SDK集成的难度，大大提升了用户
                              的开发效率，让开发者将自己的精力聚焦在业务开发上面。
                               " 														                             >> $SDK_PODFILE_NAME
  echo "  s.homepage     = '$SDK_HOMEPAGE'" 											                       >> $SDK_PODFILE_NAME
  echo "  s.license      = 'MIT'" 														                           >> $SDK_PODFILE_NAME
  echo "  s.author       = { \"$SDK_AUTOR_NAME\" => \"$SDK_AUTOR_EMAIL\" }" 						 >> $SDK_PODFILE_NAME
  echo "  s.platform     = :ios, '7.0'"                                                  >> $SDK_PODFILE_NAME
  echo "  s.source       = { :git => \"$SDK_REPOPATH\", :tag => s.version }" 				     >> $SDK_PODFILE_NAME
  echo "  s.source_files  = \"$SDK_PATH\"" 												                       >> $SDK_PODFILE_NAME
  echo "  s.framework  = \"UIKit\"" 													                           >> $SDK_PODFILE_NAME
  echo "  s.requires_arc = true" 														                             >> $SDK_PODFILE_NAME
  echo "  s.default_subspec = 'Core'" 									                                 >> $SDK_PODFILE_NAME
  echo "  "	   																			                                     >> $SDK_PODFILE_NAME

  echo "  s.subspec 'Core' do |core|" 													                         >> $SDK_PODFILE_NAME
  echo "    core.source_files = '$SDK_PATH/*.h'" 											                   >> $SDK_PODFILE_NAME
  echo "    core.public_header_files = '$SDK_PATH/*.h'" 									               >> $SDK_PODFILE_NAME
  echo "    core.vendored_libraries = '$SDK_PATH/*.a'" 									                 >> $SDK_PODFILE_NAME
  echo "    core.frameworks = 'CFNetwork', 'SystemConfiguration', 'Security'" 			     >> $SDK_PODFILE_NAME
  echo "    core.ios.library = 'c++', 'stdc++', 'z', 'sqlite3.0'" 						           >> $SDK_PODFILE_NAME
  echo "    core.xcconfig = { 'OTHER_LDFLAGS' => '-ObjC' }" 							               >> $SDK_PODFILE_NAME
  echo "  end" 																			                                     >> $SDK_PODFILE_NAME
  echo "  "    																			                                     >> $SDK_PODFILE_NAME
  
  echo "  s.subspec 'Alipay' do|ss|" 													                           >> $SDK_PODFILE_NAME
  echo "    ss.ios.vendored_frameworks = '$SDK_PATH/Channels/Alipay/AlipaySDK.framework'"  >> $SDK_PODFILE_NAME
  echo "    ss.resource = '$SDK_PATH/Channels/Alipay/AlipaySDK.bundle'" 					         >> $SDK_PODFILE_NAME
  echo "    ss.frameworks = 'CoreMotion', 'CoreTelephony'" 								               >> $SDK_PODFILE_NAME
  echo "    ss.vendored_libraries = '$SDK_PATH/Channels/Alipay/*.a'"                     >> $SDK_PODFILE_NAME
  echo "    ss.dependency '$SDK_NAME/Core'" 											                       >> $SDK_PODFILE_NAME
  echo "  end" 																			                                     >> $SDK_PODFILE_NAME
  echo "  "	  																			                                     >> $SDK_PODFILE_NAME

  echo "  s.subspec 'Wxpay' do|ss|" 													                           >> $SDK_PODFILE_NAME
  #echo "    ss.source_files = '$SDK_PATH/Channels/Wxpay/*.h'" 							             >> $SDK_PODFILE_NAME
  #echo "    ss.public_header_files = '$SDK_PATH/Channels/Wxpay/*.h'" 						         >> $SDK_PODFILE_NAME    
  echo "    ss.vendored_libraries = '$SDK_PATH/Channels/Wxpay/*.a'" 						         >> $SDK_PODFILE_NAME
  echo "    ss.dependency '$SDK_NAME/Core'" 											                       >> $SDK_PODFILE_NAME
  echo "    ss.frameworks = 'CoreTelephony'" 											                       >> $SDK_PODFILE_NAME
  echo "  end" 																			                                     >> $SDK_PODFILE_NAME
  echo "  "    																			                                     >> $SDK_PODFILE_NAME

  echo "end" 																			                                       >> $SDK_PODFILE_NAME
}

#<1> 同步网络库到本地
echo "[----Step1:同步网络仓库到本地-------]"
# git clone $SDK_REPOPATH
# cd $SDK_NAME

#<2> 代码提交到网络仓库
echo "[----Step2:将代码提交到github仓库---]"
if [ ! -f $SDK_NAME ]; then
    pod spec create $SDK_NAME
fi
configuration_podsepc 
git add *
git reset -- ./SDKInstaller
git commit -m "$SDK_UPDATE_DESCRIPTION"
git push origin master

#<3> 发布一个新的代码版本
echo "[----Step3:发布一个新的代码版本------]"
git tag -d $SDK_VERSION
git push origin --delete tag $SDK_VERSION
git tag $SDK_VERSION 
git push --tags
curl --data '{"tag_name": "'"$SDK_VERSION"'","target_commitish": "master","name": "'"$SDK_NAME V$SDK_VERSION"'","body": "'"Release of version $SDK_VERSION"'","draft": false,"prerelease": false}' https://api.github.com/repos/jinmaizhonghe/$SDK_NAME/releases?access_token=35c9e4352d638ae1298d4e02ee61a51e4d3047c8


#<4> 将库内容提交到cocoapod
echo "[----Step4:将新版本注册到cocoapod--]"
echo "2.3" > .swift-version
pod spec lint $SDK_PODFILE_NAME
pod trunk push $SDK_PODFILE_NAME --allow-warnings 
echo " "
perl -i -pe 's/SDK_VERSION=\d+\.\d+\.\K(\d+)/ $1+1 /e' SDKInstaller

echo "[----Step5:SDK发布成功-----------]"



